import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import type { InvestigationReport } from "./ai/claude";

/* Generate a downloadable investigation-report PDF with pdf-lib. */

export type ReportMeta = {
  id: string;
  title: string;
  analyst: string;
  generatedAt: Date;
  riskLevel: string;
};

const INK = rgb(0.09, 0.1, 0.15);
const MUTED = rgb(0.42, 0.45, 0.55);
const ACCENT = rgb(0.36, 0.4, 0.95);
const DANGER = rgb(0.86, 0.28, 0.28);

export async function generateReportPdf(
  report: InvestigationReport,
  meta: ReportMeta
): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  let page = pdf.addPage([595.28, 841.89]); // A4
  const margin = 54;
  const width = page.getWidth() - margin * 2;
  let y = page.getHeight() - margin;

  const newPageIfNeeded = (needed: number) => {
    if (y - needed < margin) {
      page = pdf.addPage([595.28, 841.89]);
      y = page.getHeight() - margin;
    }
  };

  const wrap = (text: string, f: PDFFont, size: number, maxWidth: number): string[] => {
    const words = text.split(/\s+/);
    const lines: string[] = [];
    let line = "";
    for (const w of words) {
      const test = line ? `${line} ${w}` : w;
      if (f.widthOfTextAtSize(test, size) > maxWidth && line) {
        lines.push(line);
        line = w;
      } else {
        line = test;
      }
    }
    if (line) lines.push(line);
    return lines;
  };

  const drawParagraph = (text: string, opts: { size?: number; f?: PDFFont; color?: typeof INK; gap?: number } = {}) => {
    const { size = 10, f = font, color = INK, gap = 5 } = opts;
    for (const ln of wrap(text, f, size, width)) {
      newPageIfNeeded(size + gap);
      page.drawText(ln, { x: margin, y, size, font: f, color });
      y -= size + gap;
    }
  };

  const heading = (text: string) => {
    y -= 10;
    newPageIfNeeded(24);
    page.drawText(text.toUpperCase(), { x: margin, y, size: 12, font: bold, color: ACCENT });
    y -= 6;
    page.drawLine({ start: { x: margin, y }, end: { x: margin + width, y }, thickness: 0.75, color: rgb(0.85, 0.86, 0.9) });
    y -= 14;
  };

  const bullets = (items: string[]) => {
    for (const item of items) {
      const lines = wrap(item, font, 10, width - 14);
      lines.forEach((ln, i) => {
        newPageIfNeeded(15);
        if (i === 0) page.drawText("•", { x: margin, y, size: 10, font: bold, color: ACCENT });
        page.drawText(ln, { x: margin + 14, y, size: 10, font, color: INK });
        y -= 15;
      });
    }
  };

  // ── Header ──
  page.drawText("FRAUDSHIELD AI", { x: margin, y, size: 20, font: bold, color: INK });
  y -= 20;
  page.drawText("Investigation Report", { x: margin, y, size: 12, font, color: MUTED });
  y -= 24;

  // Meta grid
  const metaRows: [string, string][] = [
    ["Report ID", meta.id],
    ["Generated", meta.generatedAt.toUTCString()],
    ["Analyst", meta.analyst],
    ["Risk Level", meta.riskLevel.toUpperCase()],
    ["Risk Score", `${report.riskScore}/100`],
    ["Confidence", `${Math.round(report.confidence * 100)}%`],
  ];
  for (const [k, v] of metaRows) {
    newPageIfNeeded(15);
    page.drawText(k, { x: margin, y, size: 9, font: bold, color: MUTED });
    page.drawText(v, {
      x: margin + 110,
      y,
      size: 9,
      font,
      color: k === "Risk Level" && report.riskScore >= 65 ? DANGER : INK,
    });
    y -= 15;
  }

  heading("Executive Summary");
  drawParagraph(report.executiveSummary);

  heading("Threat Assessment");
  drawParagraph(report.threatAssessment);

  if (report.evidence.length) {
    heading("Evidence");
    bullets(report.evidence);
  }

  if (report.indicators.length) {
    heading("Key Indicators");
    bullets(report.indicators);
  }

  if (report.recommendations.length) {
    heading("Recommended Actions");
    bullets(report.recommendations);
  }

  // ── Footer on the last page ──
  page.drawText("Generated by FraudShield AI · Detect. Prevent. Protect.", {
    x: margin,
    y: margin - 20,
    size: 8,
    font,
    color: MUTED,
  });

  return pdf.save();
}
